spring:
  info:
    name: "Textile Company - Project"
    Description: "One Solution for a Textile Manufacturing Company"
  datasource:
    url: jdbc:mysql://localhost:3306/textile_crm
    username: root
    password: 12345678
  jpa:
    hibernate:
#      ddl-auto: update
    properties:
      hibernate.format_sql: true
    show-sql: false
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  thymeleaf:
    view-names:
      - emailTemplates/*
  main:
    banner-mode: OFF
    lazy-initialization: true
  data:
    rest:
      base-path: "/api"
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
server:
  servlet:
    context-path: "/textile"