spring:
  info:
    name: "Textile Company - Project"
    Description: "One Solution for a Textile Manufacturing Company"
  datasource:
    url: jdbc:mysql://localhost:3306/textile_crm?createDatabaseIfNotExist=true
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  main:
    banner-mode: OFF